### ISSUE TITLE
[Blocker] Async pub/sub support for redis-rs

### ISSUE THREAD

**Issue by codesections** [tootsuite/ragequit#3]
Regardless of how #2 is resolved, we will need to be able to asynchronously interact with redis pub-sub channels.  Unfortunately, the main crate implementing a Rust API for Redis (`redis-rs`) doesn't support async interactions with pub-sub channels.

One potential solution—and my first instinct—was to also use the `redis-async` crate.  (I noticed that @sphinxc0re added `redis-async` to our dependencies, so it's possible he was thinking along the same lines).  However, after looking into the matter more closely, I noticed that `redis-async` isn't that widely used or actively maintained, so I'm reluctant to rely on it for such a crucial piece of the streaming server.

Given that, I'm inclined to at least look into adding support for async pub-sub channels to `redis-rs`.  It looks like several other people are also interested in that support, and at least two have volunteered to help with a PR adding support.  I intend to take a look at the code and see how large a lift adding that support would be and, potentially, to send a PR upstream.

**Comment by Gargron** [comment]
Okay. I am following the progress of this.
